version: "3.8"
services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/base:bullseye
    volumes:
      - ../..:/workspaces:cached
    network_mode: service:db
    command: sleep infinity
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://admin:mypassword123@db:5432/aoai-proxy

  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword123
      POSTGRES_DB: aoai-proxy
